### ISSUE TITLE
Dokka: javadoc jar is not created

### ISSUE THREAD

**Issue by Nylle** [Nylle/KotlinFixture#2]
With the new [dokka plugin 1.4.x](https://kotlin.github.io/dokka/1.4.10/user_guide/maven/usage/) it should be possible to create a javadoc-jar in Kotlin projects using Java 11.
However, when releasing, the javadoc-jar seems to be missing, which is most likely a misconfiguration of dokka.
```
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
Error:  Repository "comgithubnylle-1031" failures
Error:    Rule "javadoc-staging" failures
Error:      * Missing: no javadoc jar found in folder '/com/github/nylle/kotlinfixture/0.0.3'
```
This is the current plugin-configuration:
```
<plugin>
    <groupId>org.jetbrains.dokka</groupId>
    <artifactId>dokka-maven-plugin</artifactId>
    <version>1.4.10</version>
    <executions>
        <execution>
            <phase>pre-site</phase>
            <goals>
                <goal>dokka:javadocJar</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by dinopickaxe** [comment]
According to the dokka documentation 

[https://github.com/Kotlin/dokka/#user-content-applying-plugins-1](https://github.com/Kotlin/dokka/#user-content-applying-plugins-1)

```xml
<plugin>
    <groupId>org.jetbrains.dokka</groupId>
    <artifactId>dokka-maven-plugin</artifactId>
    <version>1.4.10</version>
    <executions>
        <execution>
            <phase>pre-site</phase>
            <goals>
                <goal>dokka</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <dokkaPlugins>
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>kotlin-as-java-plugin</artifactId>
                <version>1.4.10</version>
            </plugin>
        </dokkaPlugins>
    </configuration>
</plugin>
```

And run it with:

```sh
mvn deploy -Pdeploy
```
@Nylle

**Comment by dinopickaxe** [comment]
Fixed by removing the executing binding

```xml
<plugin>
    <groupId>org.jetbrains.dokka</groupId>
    <artifactId>dokka-maven-plugin</artifactId>
    <version>1.4.10</version>
    <configuration>
        <dokkaPlugins>
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>kotlin-as-java-plugin</artifactId>
                <version>1.4.10</version>
            </plugin>
        </dokkaPlugins>
    </configuration>
</plugin>
```

Also the **lifecycles** has to be added to the publish action and the **profiles** if needed

```sh
mvn clean dokka:javadocJar deploy
```

```yaml
- name: Action Maven Publish
  uses: samuelmeuli/action-maven-publish@v1.4.0
  with:
    maven_profiles: release
    maven_goals_phases: clean dokka:javadocJar deploy
    gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
    gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
    nexus_username: ${{ secrets.NEXUS_USERNAME }}
    nexus_password: ${{ secrets.NEXUS_PASSWORD }}
```
